-
    code: brooksblue
    family_variant: shoes_size
    categories:
        - master_men_shoes
    values:
        color: [{ locale: null, scope: null, data: blue }]
        collection: [{ locale: null, scope: null, data: [summer_2017] }]
        name: [{ locale: null, scope: null, data: 'Brooks blue' }]
        erp_name: [{ locale: en_US, scope: null, data: 'Brooks blue' }]
        description: [{ locale: en_US, scope: ecommerce, data: 'Brooks blue' }]
-
    code: brookspink
    family_variant: shoes_size
    categories:
        - master_women_shoes
    values:
        color: [{ locale: null, scope: null, data: pink }]
        collection: [{ locale: null, scope: null, data: [summer_2017] }]
        name: [{ locale: null, scope: null, data: 'Brooks pink' }]
        erp_name: [{ locale: en_US, scope: null, data: 'Brooks pink' }]
        description: [{ locale: en_US, scope: ecommerce, data: 'Brooks pink' }]
-
    code: climbingshoe
    family_variant: shoes_size
    categories:
        - master_men_shoes
        - print_shoes
        - supplier_abibas
    values:
        supplier: [{ locale: null, scope: null, data: abibas }]
        collection: [{ locale: null, scope: null, data: [summer_2017] }]
        price: [{ locale: null, scope: null, data: [{ amount: '258.00', currency: EUR }] }]
        name: [{ locale: null, scope: null, data: climbingshoe }]
        erp_name: [{ locale: en_US, scope: null, data: 'Climbing shoe' }]
        image: [{ locale: null, scope: null, data: '@file:asset/climbingshoe.jpg' }]
-
    code: converseblack
    family_variant: shoes_size
    categories:
        - master_men_shoes
        - master_women_shoes
    values:
        color: [{ locale: null, scope: null, data: black }]
        collection: [{ locale: null, scope: null, data: [summer_2017] }]
        name: [{ locale: null, scope: null, data: 'Converse black' }]
        erp_name: [{ locale: en_US, scope: null, data: 'Converse black' }]
        description: [{ locale: en_US, scope: ecommerce, data: 'Converse black' }]
        image: [{ locale: null, scope: null, data: '@file:asset/converseblack.jpg' }]
-
    code: conversered
    family_variant: shoes_size
    categories:
        - master_men_shoes
        - master_women_shoes
    values:
        color: [{ locale: null, scope: null, data: red }]
        collection: [{ locale: null, scope: null, data: [summer_2017] }]
        name: [{ locale: null, scope: null, data: 'Converse red' }]
        erp_name: [{ locale: en_US, scope: null, data: 'Converse red' }]
        description: [{ locale: en_US, scope: ecommerce, data: 'Converse red' }]
        image: [{ locale: null, scope: null, data: '@file:asset/conversered.jpg' }]
-
    code: derby
    family_variant: shoes_size
    categories:
        - master_men_shoes
        - print_shoes
        - supplier_abibas
    values:
        supplier: [{ locale: null, scope: null, data: abibas }]
        collection: [{ locale: null, scope: null, data: [summer_2016] }]
        price: [{ locale: null, scope: null, data: [{ amount: '123.00', currency: EUR }] }]
        name: [{ locale: null, scope: null, data: derby }]
        erp_name: [{ locale: en_US, scope: null, data: 'Derby shoe' }]
-
    code: dressshoe
    family_variant: shoes_size
    categories:
        - master_men_shoes
        - supplier_abibas
    values:
        supplier: [{ locale: null, scope: null, data: abibas }]
        price: [{ locale: null, scope: null, data: [{ amount: '444.00', currency: EUR }] }]
        erp_name: [{ locale: en_US, scope: null, data: 'Dress shoe' }]
        image: [{ locale: null, scope: null, data: '@file:asset/dressshoe.jpg' }]
-
    code: elegance
    family_variant: shoes_size
    categories:
        - master_men_shoes
    values:
        color: [{ locale: null, scope: null, data: black }]
        collection: [{ locale: null, scope: null, data: [summer_2017] }]
        name: [{ locale: null, scope: null, data: elegance }]
        erp_name: [{ locale: en_US, scope: null, data: Elegance }]
        image: [{ locale: null, scope: null, data: '@file:asset/elegance.jpg' }]
-
    code: galesh
    family_variant: shoes_size
    categories:
        - master_men_shoes
        - print_shoes
        - supplier_abibas
    values:
        supplier: [{ locale: null, scope: null, data: abibas }]
        collection: [{ locale: null, scope: null, data: [summer_2016] }]
        price: [{ locale: null, scope: null, data: [{ amount: '144.00', currency: EUR }] }]
        name: [{ locale: null, scope: null, data: galesh }]
        erp_name: [{ locale: en_US, scope: null, data: 'Galesh shoe' }]
-
    code: jellyshoes
    family_variant: shoes_size
    categories:
        - master_women_shoes
        - supplier_abibas
    values:
        supplier: [{ locale: null, scope: null, data: abibas }]
        collection: [{ locale: null, scope: null, data: [winter_2016] }]
        price: [{ locale: null, scope: null, data: [{ amount: '176.00', currency: EUR }] }]
        name: [{ locale: null, scope: null, data: jellyshoes }]
        erp_name: [{ locale: en_US, scope: null, data: 'Jelly shoe' }]
-
    code: moccasin
    family_variant: shoes_size
    categories:
        - master_men_shoes
        - print_shoes
        - supplier_abibas
    values:
        supplier: [{ locale: null, scope: null, data: abibas }]
        collection: [{ locale: null, scope: null, data: [spring_2015] }]
        price: [{ locale: null, scope: null, data: [{ amount: '322.00', currency: EUR }] }]
        name: [{ locale: null, scope: null, data: moccasin }]
        erp_name: [{ locale: en_US, scope: null, data: Moccasin }]
-
    code: stilleto
    family_variant: shoes_size
    categories:
        - master_women_shoes
        - supplier_abibas
    values:
        supplier: [{ locale: null, scope: null, data: abibas }]
        collection: [{ locale: null, scope: null, data: [spring_2016] }]
        price: [{ locale: null, scope: null, data: [{ amount: '123.00', currency: EUR }] }]
        name: [{ locale: null, scope: null, data: stilleto }]
        erp_name: [{ locale: en_US, scope: null, data: Stiletto }]
        image: [{ locale: null, scope: null, data: '@file:asset/stilleto.jpg' }]
-
    code: stock
    family_variant: shoes_size
    categories:
        - master_women_shoes
    values:
        color: [{ locale: null, scope: null, data: red }]
        collection: [{ locale: null, scope: null, data: [summer_2017] }]
        name: [{ locale: null, scope: null, data: stock }]
        erp_name: [{ locale: en_US, scope: null, data: Stock }]
-
    code: model-braided-hat
    family_variant: accessories_size
    categories:
        - master_accessories_hats
    values:
        color: [{ locale: null, scope: null, data: grey }]
        material: [{ locale: null, scope: null, data: wool }]
        collection: [{ locale: null, scope: null, data: [summer_2017] }]
        name: [{ locale: null, scope: null, data: 'Braided hat ' }]
        description: [{ locale: en_US, scope: ecommerce, data: 'Braided hat ' }]
        image: [{ locale: null, scope: null, data: '@file:asset/model-braided-hat.jpg' }]
-
    code: model-running-shoes
    family_variant: shoes_size_color
    categories:
        - master_men_shoes
    values:
        material: [{ locale: null, scope: null, data: leather }]
        collection: [{ locale: null, scope: null, data: [summer_2017] }]
        name: [{ locale: null, scope: null, data: 'Running shoes' }]
        description: [{ locale: en_US, scope: ecommerce, data: 'Running shoes' }]
-
    code: model-running-shoes-l
    family_variant: shoes_size_color
    parent: model-running-shoes
    values:
        size: [{ locale: null, scope: null, data: l }]
        variation_name: [{ locale: en_US, scope: null, data: 'Running shoes L' }]
-
    code: model-running-shoes-m
    family_variant: shoes_size_color
    parent: model-running-shoes
    values:
        size: [{ locale: null, scope: null, data: m }]
        variation_name: [{ locale: en_US, scope: null, data: 'Running shoes M' }]
-
    code: model-running-shoes-s
    family_variant: shoes_size_color
    parent: model-running-shoes
    values:
        size: [{ locale: null, scope: null, data: s }]
        variation_name: [{ locale: en_US, scope: null, data: 'Running shoes S' }]
